{{ range .Values.apps }}
{{ $res := .resources | default dict -}}
{{ $resreq := $res.requests | default dict -}}
{{ $reslim := $res.limits | default dict -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-synapse-{{ .name }}
spec:
  replicas: {{ .replicas | default $.Values.global.replicas }}
  selector:
    matchLabels:
      app: core-synapse-{{ .name }}
  template:
    metadata:
      labels:
        app: core-synapse-{{ .name }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: core-synapse-{{ .name }}
        image: "{{ $.Values.global.repository }}:core-synapse-{{ .name }}-{{ .version }}"
        ports:
          - containerPort: {{ .port }}
        env:
        {{- if .env }}
          {{- toYaml .env | nindent 10 }}
        {{- end }}
          - name: env
            value: {{ $.Values.global.env | default "sit" }}
        resources:
          requests:
            memory: {{ $resreq.memory | default "128Mi" }}
            cpu: {{ $resreq.cpu | default "250m" }}
          limits:
            memory: {{ $reslim.memory | default "256Mi" }}
            cpu: {{ $reslim.cpu | default "500m" }}




{{- end }}
