apiVersion: v1
name: core-synapse
description: Helm chart for deploying the Core Synapse platform.
version: 0.1.0
appVersion: "latest"

global:
  repository: devscouse/privatelibrary
  replicas: 1

apps:

  - name: api
    port: 8000
    version: 0.0.7
    service:
      type: NodePort

  - name: sentiment-analysis
    port: 5000
    version: 0.0.6
    service:
      type: ClusterIP

  - name: ui
    port: 8080
    version: 0.0.1
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"
    service:
      type: NodePort

