apiVersion: v1
name: core-synapse
description: Helm chart for deploying the Core Synapse platform.
version: 0.1.0
appVersion: "latest"

global:
  repository: devscouse/privatelibrary
  replicas: 1
  env: sit

apps:

  - name: api
    port: 8000
    version: "0.0.10"
    service:
      type: ClusterIP

  - name: sentiment-analysis
    port: 5000
    version: "0.0.8"
    service:
      type: ClusterIP

  - name: ui
    port: 8080
    version: "596cc23"
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"
    service:
      type: NodePort
    env:
      - name: svc_api_url
        value: http://core-synapse-api:8000/

